import assert from "node:assert/strict";
import test from "node:test";
import { openDatabase } from "../lib/server/db/connection";
import { KnowledgeBaseRepository } from "../lib/server/repositories/knowledgeBaseRepository";
import { SessionRepository } from "../lib/server/repositories/sessionRepository";
import { KnowledgeRepository } from "../lib/server/repositories/knowledgeRepository";
import { randomUUID } from "node:crypto";
import path from "node:path";
import os from "node:os";
import { NextRequest } from "next/server";
import type Database from "better-sqlite3";
import * as baseApi from "../app/api/knowledge-bases/route";
import * as knowledgeApi from "../app/api/knowledge/route";
import * as qaApi from "../app/api/qa-bank/route";
import * as sessionApi from "../app/api/sessions/route";
import { EMPTY_KNOWLEDGE_PACK } from "../lib/knowledge/types";

test("local and shared base CRUD rejects foreign profiles and linked deletion", context => {
  const database = openDatabase(":memory:");
  context.after(() => database.close());
  const repository = new KnowledgeBaseRepository(database);
  assert.equal(repository.list()[0].id, "personal-knowledge");
  const personal = repository.create({ name: "Personal", kind: "PERSONAL" });
  const job = repository.create({ name: "Role", kind: "JOB", company: "Example" });
  const reference = repository.create({ name: "Guide", kind: "REFERENCE" });
  assert.equal(repository.update(job.id, { name: "Updated", company: "Company" }).name, "Updated");
  assert.deepEqual(repository.validateSelections([personal.id, job.id, reference.id], "MEETING").map(base => base.kind), ["PERSONAL", "JOB", "REFERENCE"]);
  assert.throws(() => repository.validateSelections([], "MEETING"), /Select/);
  assert.deepEqual(repository.validateSelections([], "INTERVIEWER"), []);
  assert.throws(() => repository.require("bad"), /Invalid/);
  database.prepare("INSERT INTO profiles(id,kind,display_name,created_at,updated_at) VALUES ('other','CONTACT','Other','now','now')").run();
  database.prepare("UPDATE knowledge_bases SET profile_id='other' WHERE id=?").run(personal.id);
  assert.throws(() => repository.require(personal.id), /unavailable/);
  assert.ok(!repository.list().some(base => base.id === personal.id));
  database.prepare("INSERT INTO sessions(id,local_profile_id,mode,started_at) VALUES ('session','local-user','MEETING','now')").run();
  database.prepare("INSERT INTO session_knowledge_bases VALUES ('session',?,'JOB_CONTEXT')").run(job.id);
  assert.throws(() => repository.delete(job.id), /linked/);
  assert.throws(() => repository.delete("personal-knowledge"), /default/);
  repository.delete(reference.id);
  assert.throws(() => repository.require(reference.id), /unavailable/);
});

test("session selection updates are atomic, survive reload and preserve absent selections", context => {
  const database = openDatabase(":memory:");
  context.after(() => database.close());
  const bases = new KnowledgeBaseRepository(database);
  const sessions = new SessionRepository(database);
  const job = bases.create({ name: "Job", kind: "JOB" });
  const reference = bases.create({ name: "Reference", kind: "REFERENCE" });
  const info = { company: "", details: "", callType: "meeting" as const, knowledgeBaseIds: ["personal-knowledge", job.id, reference.id] };
  sessions.start({ id: "session", ownerTabId: "tab", sessionInfo: info });
  assert.deepEqual(sessions.get("session")?.sessionInfo?.knowledgeBaseIds, [...info.knowledgeBaseIds].sort());
  assert.deepEqual((database.prepare("SELECT usage_role FROM session_knowledge_bases WHERE session_id='session' ORDER BY usage_role").all() as Array<{ usage_role: string }>).map(row => row.usage_role), ["JOB_CONTEXT", "PERSONAL_FACTS", "REFERENCE"]);
  sessions.start({ id: "session", ownerTabId: "tab", sessionInfo: { company: "Changed", details: "", callType: "meeting" } });
  assert.equal(sessions.get("session")?.sessionInfo?.knowledgeBaseIds?.length, 3);
  assert.throws(() => sessions.start({ id: "session", ownerTabId: "tab", sessionInfo: { ...info, company: "Wrong", knowledgeBaseIds: [job.id, "bad"] } }), /Invalid/);
  assert.equal(sessions.get("session")?.sessionInfo?.company, "Changed");
  assert.equal(sessions.get("session")?.sessionInfo?.knowledgeBaseIds?.length, 3);
  assert.throws(() => sessions.start({ id: "failed", ownerTabId: "tab", sessionInfo: { ...info, knowledgeBaseIds: [] } }), /Select/);
  assert.equal(sessions.get("failed"), null);
  sessions.appendTurns("session", [{ id: "turn", sequenceId: 1, speaker: "me", text: "Hello", timestamp: new Date().toISOString() }], "tab");
  assert.throws(() => sessions.start({ id: "session", ownerTabId: "tab", sessionInfo: { ...info, callType: "taking_interview", knowledgeBaseIds: [job.id] } }), /locked/);
  assert.equal(sessions.get("session")?.sessionInfo?.knowledgeBaseIds?.length, 3);
});

test("originals and availability are base scoped; imported sources without bytes are unavailable", context => {
  const database = openDatabase(":memory:");
  context.after(() => database.close());
  const bases = new KnowledgeBaseRepository(database);
  const knowledge = new KnowledgeRepository(database);
  const job = bases.create({ name: "Job", kind: "JOB" });
  const source = { id: "source", filename: "notes.txt", type: "notes" as const, uploadedAt: "2020", summary: "", facts: [], keywords: [] };
  knowledge.addSource(source, job.id, { bytes: Buffer.from("original"), mimeType: "text/plain" });
  knowledge.addSource(source);
  assert.equal(bases.original(job.id, source.id).bytes.toString(), "original");
  assert.deepEqual(bases.sourceAvailability(job.id), { source: true });
  assert.deepEqual(bases.sourceAvailability(), { source: false });
  assert.throws(() => bases.original("personal-knowledge", source.id), /unavailable/);
  knowledge.clear();
  assert.equal(bases.original(job.id, source.id).bytes.toString(), "original");
  bases.delete(job.id);
  assert.equal(database.prepare("SELECT 1 FROM knowledge_documents WHERE knowledge_base_id=?").get(job.id), undefined);
});

test("knowledge scope HTTP APIs isolate editing, caches and downloads with safe headers", async context => {
  const database = openDatabase(":memory:");
  const filename = path.join(os.tmpdir(), `knowledge-scope-${randomUUID()}.db`);
  const previousPath = process.env.COPILOT_DB_PATH;
  const globals = globalThis as typeof globalThis & { copilotDatabases?: Map<string, Database.Database> };
  const connections = globals.copilotDatabases ||= new Map();
  connections.set(filename, database);
  process.env.COPILOT_DB_PATH = filename;
  context.after(() => {
    if (previousPath === undefined) delete process.env.COPILOT_DB_PATH;
    else process.env.COPILOT_DB_PATH = previousPath;
    connections.delete(filename);
    database.close();
  });
  const request = (endpoint: string, method = "GET", body?: object) => new NextRequest(`http://localhost/api/${endpoint}`, { method, ...(body ? { headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) } : {}) });
  const created = await baseApi.POST(request("knowledge-bases", "POST", { name: "Job", kind: "JOB", company: "Example" }));
  assert.equal(created.status, 201);
  const { base } = await created.json();
  assert.equal(base.company, "Example");
  assert.equal((await baseApi.GET()).status, 200);
  assert.equal((await baseApi.PUT(request("knowledge-bases", "PUT", { baseId: base.id, name: "Updated" }))).status, 200);
  assert.equal((await baseApi.POST(request("knowledge-bases", "POST", { name: "", kind: "JOB" }))).status, 400);
  assert.equal((await baseApi.DELETE(request("knowledge-bases?baseId=personal-knowledge", "DELETE"))).status, 409);
  const knowledge = new KnowledgeRepository(database);
  const source = { id: "source", filename: 'unsafe\r\n"name.txt', type: "notes" as const, uploadedAt: "2020", summary: "", facts: [], keywords: [] };
  knowledge.addSource(source, base.id, { bytes: Buffer.from("original"), mimeType: "text/plain\r\nUnsafe: header" });
  knowledge.addSource({ ...source, filename: "legacy.txt" });
  assert.equal((await (await knowledgeApi.GET(request(`knowledge?baseId=${base.id}`))).json()).sources[0].hasOriginal, true);
  assert.equal((await (await knowledgeApi.GET(request("knowledge"))).json()).sources[0].hasOriginal, false);
  const download = await knowledgeApi.GET(request(`knowledge?baseId=${base.id}&sourceId=source&download=1`));
  assert.equal(download.status, 200);
  assert.equal(await download.text(), "original");
  assert.ok(!/[\r\n]/.test(download.headers.get("Content-Disposition")!));
  assert.equal(download.headers.get("Content-Type"), "application/octet-stream");
  assert.equal((await knowledgeApi.GET(request("knowledge?sourceId=source&download=1"))).status, 404);
  const pack = { ...structuredClone(EMPTY_KNOWLEDGE_PACK), facts: ["Job only"] };
  assert.equal((await knowledgeApi.PUT(request("knowledge", "PUT", { baseId: base.id, pack }))).status, 200);
  assert.equal((await knowledgeApi.DELETE(request("knowledge?sourceId=source", "DELETE"))).status, 200);
  assert.deepEqual((await (await knowledgeApi.GET(request(`knowledge?baseId=${base.id}`))).json()).stats.facts, 1);
  assert.equal((await qaApi.POST(request("qa-bank", "POST", { baseId: base.id, entry: { questions: ["Job question"], answer: "Job answer" } }))).status, 200);
  assert.equal((await qaApi.POST(request("qa-bank", "POST", { entry: { questions: ["Personal question"], answer: "Personal answer" } }))).status, 200);
  const jobBank = await (await qaApi.GET(request(`qa-bank?baseId=${base.id}`))).json();
  assert.equal(jobBank.entries[0].questions[0], "Job question");
  assert.equal((await (await qaApi.GET(request("qa-bank"))).json()).entries[0].questions[0], "Personal question");
  assert.equal((await qaApi.PUT(request("qa-bank", "PUT", { baseId: base.id, bank: { entries: [{ questions: ["Other job question"], answer: "Other answer" }] }, mode: "merge" }))).status, 200);
  assert.equal((await qaApi.DELETE(request(`qa-bank?baseId=${base.id}&entryId=${encodeURIComponent(jobBank.entries[0].id)}`, "DELETE"))).status, 200);
  assert.equal((await qaApi.DELETE(request(`qa-bank?baseId=${base.id}`, "DELETE"))).status, 200);
  assert.equal((await (await qaApi.GET(request("qa-bank"))).json()).count, 1);
  const sessions = new SessionRepository(database);
  sessions.start({ id: "active", ownerTabId: "tab", sessionInfo: { company: "", details: "", callType: "meeting", knowledgeBaseIds: [base.id] } });
  assert.equal((await knowledgeApi.DELETE(request("knowledge", "DELETE"))).status, 200);
  assert.deepEqual(sessions.get("active")?.sessionInfo?.knowledgeBaseIds, [base.id]);
  assert.equal((await baseApi.DELETE(request(`knowledge-bases?baseId=${base.id}`, "DELETE"))).status, 409);
  const foreign = new KnowledgeBaseRepository(database).create({ name: "Foreign", kind: "PERSONAL" });
  database.prepare("INSERT INTO profiles(id,kind,display_name,created_at,updated_at) VALUES ('other','CONTACT','Other','now','now')").run();
  database.prepare("UPDATE knowledge_bases SET profile_id='other' WHERE id=?").run(foreign.id);
  assert.equal((await knowledgeApi.GET(request(`knowledge?baseId=${foreign.id}`))).status, 404);
  assert.equal((await qaApi.POST(request("qa-bank", "POST", { baseId: foreign.id, entry: {} }))).status, 404);
  assert.equal((await knowledgeApi.PUT(request("knowledge", "PUT", { baseId: foreign.id, pack }))).status, 404);
  assert.equal((await sessionApi.POST(request("sessions", "POST", { action: "start", id: "blocked", ownerTabId: "tab", sessionInfo: { company: "", details: "", callType: "meeting", knowledgeBaseIds: [foreign.id] } }))).status, 404);
  assert.equal((await sessionApi.POST(request("sessions", "POST", { action: "start", id: "invalid", ownerTabId: "tab", sessionInfo: { company: "", details: "", callType: "meeting", knowledgeBaseIds: Array(21).fill("personal-knowledge") } }))).status, 400);
  const form = new FormData();
  form.append("baseId", foreign.id);
  form.append("file", new File(["No extraction"], "source.txt"));
  assert.equal((await knowledgeApi.POST(new NextRequest("http://localhost/api/knowledge", { method: "POST", body: form }))).status, 404);
  assert.equal((await knowledgeApi.GET(request("knowledge?baseId=invalid"))).status, 400);
});