import assert from "node:assert/strict";
import test from "node:test";
import { openDatabase } from "../lib/server/db/connection";
import { PromptRepository, promptRepository } from "../lib/server/repositories/promptRepository";
import { GET, PUT } from "../app/api/prompts/route";

test("prompt HTTP API selects variants, saves in place and resets to the default", async (context) => {
  const db = openDatabase(":memory:");
  context.after(() => db.close());
  const repo = new PromptRepository(db);
  context.mock.method(promptRepository, "list", repo.list.bind(repo));
  context.mock.method(promptRepository, "get", repo.get.bind(repo));
  context.mock.method(promptRepository, "update", repo.update.bind(repo));
  const response = await GET(new Request("http://localhost/api/prompts?purpose=ANSWER&mode=INTERVIEWER&variant=course_admission"));
  assert.equal(response.status, 200);
  const { template } = await response.json();
  assert.equal(template.variant, "course_admission");
  assert.equal(template.customized, false);
  assert.ok(!("version" in template));
  const save = (patch: object) => PUT(new Request("http://localhost/api/prompts", { method: "PUT", body: JSON.stringify({ key: template.template_key, system_template: "Changed", user_template: "{{question}}", ...patch }) }));
  assert.equal((await save({})).status, 200);
  assert.equal((await save({ system_template: "Changed again" })).status, 200);
  const stored = await (await GET(new Request("http://localhost/api/prompts?purpose=ANSWER&mode=INTERVIEWER&variant=course_admission"))).json();
  assert.equal(stored.template.system_template, "Changed again");
  assert.equal(stored.template.customized, true);
  assert.equal((await save({ mode: "MEETING" })).status, 400);
  assert.equal((await save({ user_template: "{{unknown}}" })).status, 400);
  assert.equal((await GET(new Request("http://localhost/api/prompts?purpose=CHAT&mode=INTERVIEWER"))).status, 400);
  const reset = await save({ reset: true });
  assert.equal(reset.status, 200);
  const restored = (await reset.json()).template;
  assert.equal(restored.customized, false);
  assert.equal(restored.system_template, template.system_template);
  assert.equal((await (await GET(new Request("http://localhost/api/prompts"))).json()).templates.length, 12);
});