import assert from "node:assert/strict";
import test from "node:test";
import { openDatabase } from "../lib/server/db/connection";
import { PromptRepository } from "../lib/server/repositories/promptRepository";
import { CORE_QUALITY_RULES } from "../lib/prompts";
import { getRuntimeCallPrompt, getRuntimeInstruction, renderLiteralPlaceholders, renderRuntimePrompt } from "../lib/server/runtimePrompts";

test("runtime rendering uses the saved prompt and substitutes literals only once", (context) => {
  const db = openDatabase(":memory:");
  context.after(() => db.close());
  const repo = new PromptRepository(db);
  const row = repo.get("ANSWER", "INTERVIEWER", "course_admission");
  assert.equal(row.customized, false);
  const edited = repo.update({ key: row.template_key, system_template: "Custom {{background}}", user_template: "Ask: {{question}}" });
  assert.equal(edited.customized, true);
  const rendered = renderRuntimePrompt("ANSWER", { callType: "taking_interview", modeVariant: "course_admission" }, { background: "$& {{question}}", question: "Actual question" }, repo);
  assert.equal(rendered.promptKey, row.template_key);
  assert.equal(rendered.promptCustomized, true);
  assert.equal(getRuntimeCallPrompt({ callType: "taking_interview", modeVariant: "course_admission" }, repo).promptKey, row.template_key);
  assert.equal(rendered.prompt, "Ask: Actual question");
  assert.ok(rendered.systemInstruction.includes("Custom $& {{question}}"));
  assert.ok(rendered.systemInstruction.includes(CORE_QUALITY_RULES));
  assert.throws(() => renderLiteralPlaceholders("{{message}}"), /Missing placeholder/);
  const memory = renderRuntimePrompt("MEMORY", { callType: "taking_interview" }, { previousMemory: JSON.stringify({ summary: "old" }), recentTurns: JSON.stringify([{ text: "new" }]) }, repo);
  assert.ok(memory.prompt.includes('<PREVIOUS_MEMORY_DATA>\n{"summary":"old"}'));
  assert.throws(() => repo.get("CHAT", "MEETING"), /Invalid prompt mode/);
  assert.throws(() => repo.get("BOGUS" as any), /Invalid prompt purpose/);
  assert.throws(() => repo.update({ key: edited.template_key, system_template: "{{message}}", user_template: "" }), /placeholder/);
  assert.throws(() => repo.update({ key: edited.template_key, system_template: "{{question", user_template: "" }), /placeholder/);
  const reset = repo.update({ key: edited.template_key, reset: true });
  assert.equal(reset.customized, false);
  assert.equal(reset.system_template, row.system_template);
  assert.equal(reset.user_template, row.user_template);
  assert.deepEqual(reset.parameters, row.parameters);
  const extraction = repo.get("EXTRACTION");
  repo.update({ key: extraction.template_key, system_template: "Custom extraction style", user_template: extraction.user_template });
  const instruction = getRuntimeInstruction("EXTRACTION", { callType: "taking_interview", modeVariant: "course_admission" }, repo);
  assert.equal(instruction.promptCustomized, true);
  assert.ok(instruction.systemInstruction.includes("Custom extraction style"));
  assert.ok(instruction.systemInstruction.includes("Extract only facts explicitly supported"));
});

test("prompts seed all modes lazily, save in place without versions, and reset to the default", (context) => {
  const db = openDatabase(":memory:");
  context.after(() => db.close());
  const repo = new PromptRepository(db);
  assert.equal(db.prepare<[], { count: number }>("SELECT COUNT(*) AS count FROM prompts").get()!.count, 0);
  assert.equal(repo.list().length, 12);
  const row = repo.get("ANSWER", "INTERVIEWER", "course_admission");
  const core = CORE_QUALITY_RULES;
  const next = repo.update({ key: row.template_key, system_template: "Edited identity", user_template: row.user_template, parameters: { ...row.parameters, modeRules: "Edited mode rules" } });
  assert.equal(next.customized, true);
  assert.equal(next.parameters.modeRules, "Edited mode rules");
  repo.update({ key: row.template_key, system_template: "Edited again", user_template: row.user_template, parameters: next.parameters });
  assert.equal(new PromptRepository(db).get("ANSWER", "INTERVIEWER", "course_admission").system_template, "Edited again");
  assert.equal(db.prepare<[], { count: number }>("SELECT COUNT(*) AS count FROM prompts").get()!.count, 12);
  assert.equal(CORE_QUALITY_RULES, core);
  assert.equal(repo.get("SUMMARY", "INTERVIEWER", "course_admission").variant, "standard");
  assert.throws(() => repo.update({ key: row.template_key, system_template: "{{execute}}", user_template: "" }), /placeholder/);
  assert.throws(() => repo.update({ key: row.template_key, system_template: "Valid", user_template: "", parameters: { ...next.parameters, coreRules: "override" } }), /Unknown prompt parameter/);
  assert.throws(() => repo.update({ key: row.template_key, system_template: "Valid", user_template: "", mode: "MEETING" }), /immutable/);
  assert.throws(() => repo.update({ key: "ANSWER:MEETING:missing", reset: true }), /Prompt not found/);
  const reset = repo.update({ key: row.template_key, reset: true });
  assert.equal(reset.customized, false);
  assert.equal(reset.system_template, row.system_template);
  assert.equal(reset.parameters.modeRules, row.parameters.modeRules);
});

test("unedited prompts follow the current code defaults while customized prompts are kept", (context) => {
  const db = openDatabase(":memory:");
  context.after(() => db.close());
  const repo = new PromptRepository(db);
  const summary = repo.get("SUMMARY", "MEETING");
  const chat = repo.get("CHAT");
  repo.update({ key: chat.template_key, system_template: "My chat style", user_template: chat.user_template });
  db.prepare("UPDATE prompts SET system_template = 'Wording from an older release' WHERE template_key = ?").run(summary.template_key);
  const restarted = new PromptRepository(db);
  assert.equal(restarted.get("SUMMARY", "MEETING").system_template, summary.system_template);
  assert.equal(restarted.get("SUMMARY", "MEETING").customized, false);
  assert.equal(restarted.get("CHAT").system_template, "My chat style");
  assert.equal(restarted.get("CHAT").customized, true);
});